### ISSUE TITLE
Escrever texto para a seção "Analysis of biological networks"

### ISSUE THREAD

**Issue by jvfe** [dalmolingroup/dalmolingroup.github.io#10]
Sugestões:
- Falar do artigo do Marcel
- Falar do artigo do Raffael

**Comment by iaradsouza1** [comment]
E do artigo da Rafa, que é com redes regulatórias

**Comment by RafaellaFerraz** [comment]
Biological Network Analysis is a dynamic and interdisciplinary field that allows the integration and interpretation of complex biological information through the analysis of interactions among biological entities, whether genes, proteins, metabolites, or other molecules. This approach has enabled the identification of key biological components, regulatory mechanisms, and functional modules involved in biological pathways and diseases.

The Dalmolin Group has been using biological network analysis to uncover biological mechanisms since 2008. The first work was an integration between Protein-Protein Interactions netwotk and orthology, resulting an orthology map in order to locate the eukaryotic genes in the human apoptosis and genome-stability gene/protein-association network  (https://doi.org/10.1093/nar/gkn636). Subsequently, this approach was used to model gene networks based on transcriptional data that responds selectively to both hypoxia and acidosis (DOI: 10.2741/s352). 

Over the last decade, the group has been exploring a tool that builds networks based on regulatory units (https://bioconductor.org/packages/release/bioc/html/RTN.html) with the aim of modeling transcriptional networks and identifying master regulators associated with the investigated phenotypes. This method has helped us understand the global regulome and identify regulators responsible for triggering several diseases, including Ewing Sarcoma (https://doi.org/10.3390/cancers13081860 ), Neuroblastoma (https://doi.org/10.1371/journal.pone.0082457), Pediatric Sepsis (https://doi.org/10.3390/biomedicines9101297), and metastatic prostate cancer (https://doi.org/10.1002/cam4.6481). Our perspective for the coming years is to explore the regulatory network at the cellular level, investigating the gene interactions that occur cell to cell.
